package hello;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.RestController;
// import java.util.Date;

import hello.User;
import hello.UserRepository;

@RestController    // This means that this class is a Controller
///@RequestMapping(path="/log") // This means URL's start with /demo (after Application path)
public class MainController {
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;
	
	@CrossOrigin(origins = "http://167.99.95.217/")   //enable cross-origin on this addresss
	@GetMapping(path="/log/add") // Map ONLY GET Requests
	public @ResponseBody String addNewUser (@RequestParam String ip, @RequestParam String device, @RequestParam String location, @RequestParam String browser, @RequestParam String date) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request
		
		User info = new User();
		info.setDate(date);
		info.setDevice(device);
		info.setBrowser(browser);
		info.setIp(ip);
		info.setLocation(location);
		userRepository.save(info);
		return "success";
	}
	
	@GetMapping(path="/log/view")
	public @ResponseBody Iterable<User> getAllUsers() {
		// This returns a JSON or XML with the users
		return userRepository.findAll();
	}
}

//localhost:8080/log/add?device=samsung&date=Mon Dec 24 21:30:59 WAT 2018&location=Cameroon,Buea[latitude,longitued]&browser=chrome&ip=186.90.90.4
